### PR TITLE
Allow a message when pushing a link

### PR DESCRIPTION
**Pull request by brantje**

### CODE REVIEW

**Comment by MarvinMenzerath** [comment]
Would love to have this simple, but important addition in the module. :+1:

**Comment by alexwhitman** [comment]
@brantje Thanks for the pull request.  If you can make it backwards compatible so that the function can still be called without a message I'll get it merged.  Something like
```js
if ( ! callback) {
    url = body;
    callback = url;
    body = null;
}
```
Also the readme will need updating.

**Comment by brantje** [comment]
@MarvinMenzerath Are you ok with this?

**Comment by MarvinMenzerath** [comment]
@brantje This isn't my repository, but I like the changes. You should rather ask @alexwhitman. :smile:

**Comment by alexwhitman** [comment]
Fixed by 2064147d1d462e7ff38c99f487c5485abdfb75e0

**Pull request closed without merging**
